site_name: feishi-wiki
site_url: https://feishili.netlify.app/
theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - css/extra.css

nav:
  - 关于: index.md

  - CPP:
    - CPP/snippet/snippet_0.md
  - Qml:
    - Qml/Qml_0.md
    - Qml/Qml_1.md
    - Qml/Qml_2.md
  - JS:
    - JS/JS_0.md
  - CSharp:
    - csharp/csharp_0.md
    - csharp/csharp_1.md
  - Kotlin:
    - Kotlin/KT_0.md
  - Lua:
    - Lua/Lua_0.md
  - SQL:
    - SQL/sql_0.md
  - SDL:
    - SDL/SDL_0.md
  - Dev:
    - dev/Dev_0.md
    - dev/Dev_1.md
    - dev/vcpkg.md
    - dev/CMake_0.md
    
    - Boost:
      - dev/Boost_0.md
      - dev/boost_json.md

    - SQL:
      - dev/PostgreSQL_0.md
      - dev/SQLite.md

    - Python:
      - dev/SWIG_0.md
      - dev/Pybind11_0.md
      - dev/Cython_0.md
    
      - dev/pyside_0.md
      - dev/FastAPI_0.md

      - dev/Scrapy_0.md
      - dev/Scrapy_1.md
  
  - CP:
    - Math:
      - math/GCD_Convolution.md
      - math/sum_of_floors.md
    - Combinatorics:
      - Combinatorics/combination.md
    - dp:
      - bit_dp:
        - dp/bit_dp/bit_dp.md
        - dp/bit_dp/bit_dp_1.md

      - dp/dp_on_tree.md
      - dp/dp_on_digits.md
      - dp/range_dp.md
      - dp/dp_probability.md
    - miscellaneous:
      - miscellaneous/two_pointer.md
    - Atcoder:
      - atc/ABC006.md
      - atc/ABC012.md
      - atc/ABC015.md
      - atc/ABC016.md
      - atc/ABC036.md
      - atc/ABC040.md
      - atc/ABC110.md
      - atc/ABC127.md
      - atc/ABC128.md
      - atc/ABC133.md
      - atc/ABC152.md
      - atc/ABC160.md
      - atc/ABC170.md
      - atc/ABC208.md
      - atc/ABC284.md
      - atc/ABC325.md
      - atc/ABC343.md
      - atc/ABC349.md
    - LeetCode:
      - LeetCode/WC357.md
    - Codeforces:
      - cf/CF560.md
    - Problem:
      - problem/The_Gourmet.md
  

dev_addr: '127.0.0.1:9090'